# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_controller

  arm_controller:
    type: FollowJointTrajectory
    joints:
      - Revolute1
      - Revolute2
      - Revolute3
      - Revolute4
      - Revolute5
    action_ns: follow_joint_trajectory
    default: true